final List<String> kindnessChallenges = [
  'Smile at a stranger.',
  'Hold the door open for someone.',
  'Compliment a colleague or friend.',
  'Send a handwritten note to someone you appreciate.',
  'Donate gently used clothes to a local charity.',
  'Leave a positive online review for a business you like.',
  'Offer to help a neighbor with yard work.',
  'Pay for someone\'s coffee in line behind you.',
  'Share words of encouragement with someone going through a tough time.',
  'Leave a generous tip for a service worker.',
  'Pick up litter in your local community.',
  'Send a thoughtful text to a friend you haven\'t talked to in a while.',
  'Volunteer at a local soup kitchen or food bank.',
  'Offer your seat to someone on public transportation.',
  'Plant a tree or flowers in a public space.',
  'Send a thank-you email to someone who has helped you.',
  'Foster or adopt a pet from a local animal shelter.',
  'Help someone carry groceries to their car.',
  'Make a donation to a cause you care about.',
  'Listen actively to someone without interrupting.',
  'Share a homemade treat with your neighbors.',
  'Offer to babysit for a friend or family member.',
  'Write positive sticky notes and leave them in public places.',
  'Participate in a charity run or walk.',
  'Write a positive message on the sidewalk with chalk.',
  'Call a family member just to say you love them.',
  'Assist someone with a task they find challenging.',
  'Donate blood to a local blood bank.',
  'Create care packages for homeless individuals.',
  'Share your favorite uplifting book with a friend.',
  'Help someone with their technology or computer issues.',
  'Cook a meal for a friend or family member.',
  'Offer to mow a neighbor\'s lawn.',
  'Create and share a positive playlist with friends.',
  'Organize a neighborhood cleanup event.',
  'Send a surprise gift to a friend in the mail.',
  'Share motivational quotes on social media.',
  'Tutor someone in a subject you\'re knowledgeable about.',
  'Give up your seat for someone on public transportation.',
  'Donate toys to a children\'s hospital.',
  'Write positive affirmations and leave them for others to find.',
  'Volunteer at a local school or community center.',
  'Offer to walk a neighbor\'s dog.',
  'Help a friend with their moving day.',
  'Send a care package to a friend in need.',
  'Offer to carpool with a coworker.',
  'Create a scrapbook for a friend with shared memories.',
  'Participate in a local community garden.',
  'Organize a virtual game night for friends.',
  'Share a favorite recipe with a neighbor.',
  'Leave kind notes for your family members.',
  'Support local businesses by shopping locally.',
  'Help someone with heavy grocery bags.',
  'Send a letter of appreciation to a former teacher.',
  'Offer to do household chores for a busy friend.',
  'Participate in a local environmental cleanup event.',
  'Share educational resources with others.',
  'Leave positive comments on social media posts.',
  'Teach someone a new skill or hobby.',
  'Offer to be a workout buddy for a friend.',
  'Donate art supplies to a local school.',
  'Share a positive news story with friends.',
  'Create a "Kindness Jar" with uplifting notes for yourself or others.',
  'Offer to be a mentor to someone.',
  'Write a letter to a deployed military member.',
  'Support a friend\'s small business.',
  'Offer to help a coworker with a project.',
  'Share your favorite inspirational podcast.',
  'Send a care package to a college student.',
  'Help someone with grocery shopping.',
  'Offer to water your neighbor\'s plants.',
  'Share a joke or funny video to brighten someone\'s day.',
  'Assist someone with learning a new language.',
  'Share positive quotes on workplace bulletin boards.',
  'Offer to be a study partner for a student.',
  'Volunteer at a local animal rescue organization.',
  'Help someone with moving furniture.',
  'Create and share a gratitude journal with friends.',
  'Share tips on stress relief with others.',
  'Offer to pick up essentials for an elderly neighbor.',
  'Write a positive letter to your future self.',
  'Share your favorite inspirational book with a friend.',
  'Offer to take a friend\'s pet for a walk.',
  'Support a friend in pursuing a personal goal.',
  'Create a kindness scavenger hunt for your community.',
  'Leave a kind note for a coworker.',
  'Offer to help a friend with gardening.',
  'Share a motivational TED Talk with friends.',
  'Offer to be a volunteer driver for someone in need.',
  'Help a friend with home organization.',
  'Share resources on mental health and well-being.',
  'Offer to proofread a friend\'s document or resume.',
  'Support a local artist by purchasing their work.',
  'Share your favorite recipe for a healthy meal.',
  'Offer to assist someone with car maintenance.',
  'Create a positive and inclusive online community.',
  'Share your umbrella with someone on a rainy day.',
  'Offer to teach a friend a new hobby.',
  'Support a friend\'s fundraising efforts for a cause.',
  'Encourage someone to pursue their passion.',
];
