List<String> motivationalQuotes = [
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.",
  "You are never too old to set another goal or to dream a new dream.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Just when the caterpillar thought the world was ending, he turned into a butterfly.",
  "There are no limits to what you can accomplish, except the limits you place on your own thinking.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Believe you can and you’re halfway there.",
  "The only way to do great work is to love what you do.",
  "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "There is no substitute for hard work.",
  "The only place where success comes before work is in the dictionary.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Setting goals is the first step into turning the invisible into the visible.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing.",
];
