final List<String> alberteinstein = [
  'assets/Images/persons/AlbertEinstein/1.jpg',
  'assets/Images/persons/AlbertEinstein/2.jpg',
  'assets/Images/persons/AlbertEinstein/3.jpg',
  'assets/Images/persons/AlbertEinstein/4.jpg',
  'assets/Images/persons/AlbertEinstein/5.jpg',
  'assets/Images/persons/AlbertEinstein/6.jpg',
  'assets/Images/persons/AlbertEinstein/7.jpg',
  'assets/Images/persons/AlbertEinstein/8.jpg',
  'assets/Images/persons/AlbertEinstein/9.jpg',
  'assets/Images/persons/AlbertEinstein/10.jpg',
];
final List<String> andrewtate = [
  'assets/Images/persons/AndrewTate/1.jpg',
  'assets/Images/persons/AndrewTate/2.jpg',
  'assets/Images/persons/AndrewTate/3.jpg',
  'assets/Images/persons/AndrewTate/4.jpg',
  'assets/Images/persons/AndrewTate/5.jpg',
  'assets/Images/persons/AndrewTate/6.jpg',
  'assets/Images/persons/AndrewTate/7.jpg',
  'assets/Images/persons/AndrewTate/8.jpg',
  'assets/Images/persons/AndrewTate/9.jpg',
  'assets/Images/persons/AndrewTate/10.jpg',
];
final List<String> apj = [
  'assets/Images/persons/APJ/1.jpg',
  'assets/Images/persons/APJ/2.jpg',
  'assets/Images/persons/APJ/3.jpg',
  'assets/Images/persons/APJ/4.jpg',
  'assets/Images/persons/APJ/5.jpg',
  'assets/Images/persons/APJ/6.jpg',
  'assets/Images/persons/APJ/7.jpg',
  'assets/Images/persons/APJ/8.jpg',
  'assets/Images/persons/APJ/9.jpg',
  'assets/Images/persons/APJ/10.jpg',
];
final List<String> billgates = [
  'assets/Images/persons/BillGates/1.jpg',
  'assets/Images/persons/BillGates/2.jpg',
  'assets/Images/persons/BillGates/3.jpg',
  'assets/Images/persons/BillGates/4.jpg',
  'assets/Images/persons/BillGates/5.jpg',
  'assets/Images/persons/BillGates/6.jpg',
  'assets/Images/persons/BillGates/7.jpg',
  'assets/Images/persons/BillGates/8.jpg',
  'assets/Images/persons/BillGates/9.jpg',
  'assets/Images/persons/BillGates/10.jpg',
];
// ignore: non_constant_identifier_names
final List<String> elon_musk = [
  'assets/Images/persons/ElonMusk/1.jpg',
  'assets/Images/persons/ElonMusk/2.jpg',
  'assets/Images/persons/ElonMusk/3.jpg',
  'assets/Images/persons/ElonMusk/4.jpg',
  'assets/Images/persons/ElonMusk/5.jpg',
  'assets/Images/persons/ElonMusk/6.jpg',
  'assets/Images/persons/ElonMusk/7.jpg',
  'assets/Images/persons/ElonMusk/8.jpg',
  'assets/Images/persons/ElonMusk/9.jpg',
  'assets/Images/persons/ElonMusk/10.jpg',
];
final List<String> gurugopaldas = [
  'assets/Images/persons/GuruGopalDas/1.jpg',
  'assets/Images/persons/GuruGopalDas/2.jpg',
  'assets/Images/persons/GuruGopalDas/3.jpg',
  'assets/Images/persons/GuruGopalDas/4.jpg',
  'assets/Images/persons/GuruGopalDas/5.jpg',
  'assets/Images/persons/GuruGopalDas/6.jpg',
  'assets/Images/persons/GuruGopalDas/7.jpg',
  'assets/Images/persons/GuruGopalDas/8.jpg',
  'assets/Images/persons/GuruGopalDas/9.jpg',
  'assets/Images/persons/GuruGopalDas/10.jpg',
];
final List<String> msd = [
  'assets/Images/persons/MSD/1.jpg',
  'assets/Images/persons/MSD/2.jpg',
  'assets/Images/persons/MSD/3.jpg',
  'assets/Images/persons/MSD/4.jpg',
  'assets/Images/persons/MSD/5.jpg',
  'assets/Images/persons/MSD/6.jpg',
  'assets/Images/persons/MSD/7.jpg',
  'assets/Images/persons/MSD/8.jpg',
  'assets/Images/persons/MSD/9.jpg',
  'assets/Images/persons/MSD/10.jpg',
];
final List<String> sadhguru = [
  'assets/Images/persons/SadhGuru/1.jpg',
  'assets/Images/persons/SadhGuru/2.jpg',
  'assets/Images/persons/SadhGuru/3.jpg',
  'assets/Images/persons/SadhGuru/4.jpg',
  'assets/Images/persons/SadhGuru/5.jpg',
  'assets/Images/persons/SadhGuru/6.jpg',
  'assets/Images/persons/SadhGuru/7.jpg',
  'assets/Images/persons/SadhGuru/8.jpg',
  'assets/Images/persons/SadhGuru/9.jpg',
  'assets/Images/persons/SadhGuru/10.jpg',
];
final List<String> swamivivekananda = [
  'assets/Images/persons/SwamiVivekananda/1.jpg',
  'assets/Images/persons/SwamiVivekananda/2.jpg',
  'assets/Images/persons/SwamiVivekananda/3.jpg',
  'assets/Images/persons/SwamiVivekananda/4.jpg',
  'assets/Images/persons/SwamiVivekananda/5.jpg',
  'assets/Images/persons/SwamiVivekananda/6.jpg',
  'assets/Images/persons/SwamiVivekananda/7.jpg',
  'assets/Images/persons/SwamiVivekananda/8.jpg',
  'assets/Images/persons/SwamiVivekananda/9.jpg',
  'assets/Images/persons/SwamiVivekananda/10.jpg',
];
final List<String> viratkohli = [
  'assets/Images/persons/ViratKohli/1.jpg',
  'assets/Images/persons/ViratKohli/2.jpg',
  'assets/Images/persons/ViratKohli/3.jpg',
  'assets/Images/persons/ViratKohli/4.jpg',
  'assets/Images/persons/ViratKohli/5.jpg',
  'assets/Images/persons/ViratKohli/6.jpg',
  'assets/Images/persons/ViratKohli/7.jpg',
  'assets/Images/persons/ViratKohli/8.jpeg',
  'assets/Images/persons/ViratKohli/9.jpg',
  'assets/Images/persons/ViratKohli/10.jpg',
];

Map<String, List<String>> quoteMap = {
  'AlbertEinstein': [
    "Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution.",
    "The important thing is not to stop questioning. Curiosity has its own reason for existing.",
    "Logic will get you from A to Z; imagination will get you everywhere.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "The only source of knowledge is experience.",
    "Anyone who has never made a mistake has never tried anything new.",
    "Strive not to be a success, but rather to be of value.",
    "The world is a dangerous place to live; not because of the people who are evil, but because of the people who don't do anything about it.",
    "A person who never made a mistake never tried anything new.",
    "Education is what remains after one has forgotten what one has learned in school.",
  ],
  'AndrewTate': [
    "All the successful people I know have been in a combat sport at some point in their lives.",
    "Most people are not willing to work hard enough to get what they want. It's that simple.",
    "Life is a competition. Winners win, and losers lose. It's as simple as that.",
    "There's no such thing as overtraining, only under eating and under sleeping.",
    "You have to be selfish to be successful.",
    "Money is a tool. Use it to get what you want.",
    "You can't negotiate attraction.",
    "Hard work beats talent when talent doesn't work hard.",
    "You’ve been given another day of life. How will you use it? Will you wait until tomorrow as you’ve done for years or decide today is the day you commit to excellence?",
    "Your future is the result of your daily actions. You’re defined by what you do today. Lazy now, loser later. Get to work.",
  ],
  'APJ': [
    "Dream, Dream, Dream. Dreams transform into thoughts and thoughts result in action.",
    "All of us do not have equal talent. But, all of us have an equal opportunity to develop our talents.",
    "You have to dream before your dreams can come true.",
    "If you want to shine like a sun, first burn like a sun.",
    "Don't take rest after your first victory because if you fail in second, more lips are waiting to say that your first victory was just luck.",
    "Failure will never overtake me if my determination to succeed is strong enough.",
    "Great dreams of great dreamers are always transcended.",
    "Thinking is the capital, Enterprise is the way, Hard Work is the solution.",
    "Man needs his difficulties because they are necessary to enjoy success.",
    "Without your involvement, you can't succeed. With your involvement, you can't fail.",
  ],
  'BillGates': [
    "Your most unhappy customers are your greatest source of learning.",
    "It's fine to celebrate success, but it is more important to heed the lessons of failure.",
    "We always overestimate the change that will occur in the next two years and underestimate the change that will occur in the next ten. Don't let yourself be lulled into inaction.",
    "If you are born poor it's not your mistake, but if you die poor it's your mistake.",
    "We need to find a way to make the aspects of capitalism that serve wealthier people serve poorer people as well.",
    "Your school may have done away with winners and losers, but life has not. In some schools, they have abolished failing grades; they'll give you as many chances as you want to get the right answer. This doesn't bear the slightest resemblance to anything in real life.",
    "I believe that if you show people the problems and you show them the solutions they will be moved to act.",
    "As we look ahead into the next century, leaders will be those who empower others.",
    "Don't compare yourself with anyone in this world. If you do so, you are insulting yourself.",
    "If you can't make it good, at least make it look good.",
  ],
  'ElonMusk': [
    "When something is important enough, you do it even if the odds are not in your favor.",
    "Persistence is very important. You should not give up unless you are forced to give up.",
    "I think it is possible for ordinary people to choose to be extraordinary.",
    "Failure is an option here. If things are not failing, you are not innovating enough.",
    "I would like to die on Mars. Just not on impact.",
    "If you get up in the morning and think the future is going to be better, it is a bright day. Otherwise, it's not.",
    "The first step is to establish that something is possible; then probability will occur.",
    "Some people don't like change, but you need to embrace change if the alternative is disaster.",
    "I think that's the single best piece of advice: constantly think about how you could be doing things better and questioning yourself.",
    "The biggest mistake we made as a company was betting too much on HTML5 over native.",
  ],
  'GuruGopalDas': [
    'If you do what you love, you will never have to work a day in your life.',
    'Life is a difficult exam. Many people fail because they try to copy others, not realizing that everyone has a different question paper.',
    'Forgiveness is a complex concept. We must understand it thoroughly to be able to internalize it.',
    'Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.',
    'The first step in selflessness is to practise it with our family.',
    'Physical violence is inflicted with weapons, but emotional violence is inflicted with words; words can leave invisible scars that can take years, or even lifetimes, to heal.',
    'We can increase our scope of selflessness beyond our family by serving our community, city or even nation.',
    'The need for instant gratification can wreak havoc on our sleep cycle and quality.',
    'There are many ways to perceive others. We should start choosing the one which magnifies the positive and avoids the negative.',
    'Always seeing the best in people and choosing to avoid their faults.',
  ],
  'MSD': [
    "I am not a cricketing brain. I watch cricket, but don't follow it keenly.",
    "I am the kind who doesn't press the panic button too much. Once I know the problem, I'll start working towards solving it.",
    "I'm not very serious about cricket. I don't watch cricket much.",
    "I play cricket for the love of the game. I don't know any other way to play it.",
    "It's important to learn and not repeat the same mistakes. What's done is done.",
    "I am happy with the way I am. I am not someone who is very attached to the past.",
    "As a sportsman, you'll go through a lot of ups and downs, both in form and in life.",
    "One quality that I have is I don't give up. I don't take negative opinions.",
    "What doesn't kill you makes you strong, and today, I'm alive.",
    "As of now, I don't have any immediate plans to retire. But at the same time, I'm also not saying that I'm not going to retire.",
  ],
  'SadhGuru': [
    "The sign of intelligence is that you are constantly wondering. Idiots are always dead sure about every damn thing they are doing in their life.",
    "If you resist change, you resist life.",
    "The only way you can conquer the world is through love.",
    "If you do not know how to handle yourself, then who else will handle you?",
    "Your life is your making. If you do not do what you want with it, no one else will.",
    "The quality of your life depends on how well you manage your body, mind, emotions, situations, and relationships.",
    "The fear is simply because you are not living with life, you are living in your mind.",
    "There is no such thing as work-life balance. It is all life. The balance has to be within you.",
    "If you want to be successful, don’t seek success – seek competence, empowerment; do nothing short of the best that you can do.",
    "The most important thing is that you are alive – that's the biggest thing. If you are alive, there is possibility. If you are not alive, there is no possibility.",
  ],
  'SwamiVivekananda': [
    "Arise, awake, and stop not until the goal is reached.",
    "You cannot believe in God until you believe in yourself.",
    "Strength is life, weakness is death.",
    "In a conflict between the heart and the brain, follow your heart.",
    "Stand up, be bold, be strong. Take the whole responsibility on your own shoulders, and know that you are the creator of your own destiny.",
    "Take risks in your life, if you win, you can lead! If you lose, you can guide!",
    "The greatest sin is to think yourself weak.",
    "Condemn none: if you can stretch out a helping hand, do so. If you cannot, fold your hands, bless your brothers, and let them go their own way.",
    "The more we come out and do good to others, the more our hearts will be purified, and God will be in them.",
    "In a day, when you don't come across any problems - you can be sure that you are travelling in a wrong path.",
  ],
  'ViratKohli': [
    "The only thing I have done is worked hard, and the only thing I have seen is success.",
    "Self-belief and hard work will always earn you success.",
    "I like to be myself, and I don't pretend. For instance, I don't dress up for occasions; I am what I am.",
    "I love playing under pressure, and I've always believed that's when you get the best out of yourself.",
    "I never think for other people, what they say about me or what they think about me.",
    "For me, cricket is the only thing that I'm very passionate about. And I'm a very patriotic person.",
    "I focus on my process and I just try and do the best I can for the team.",
    "The people you hang out with, and the decisions you make are the ones that change your life.",
    "I have always believed that one should not be scared of losing, I think that really is the key.",
    "My only aim is just to keep pushing hard, keep at it and keep getting better day by day.",
  ],
};
