name: myapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.0
  firebase_auth: ^4.16.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  audio_video_progress_bar: ^2.0.1
  firebase_storage: ^11.6.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.0
  video_player: ^2.8.2
  http: ^1.2.0
  icons_plus: ^5.0.0
  video_player_control_panel: ^1.1.1
  flutter_xlider: ^3.1.1
  cloud_firestore: ^4.15.4
  image_picker: ^1.0.7
  circular_countdown_timer: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    #logo and splash screen image
    - assets/SVGS/Splash/newlogo.svg
    - assets/Images/logos.jpg

    #study Music
    - assets/Images/Study_image/study_music.jpg

    #video
    - assets/Video/newvideo.mp4
    - assets/Video/video1.mp4

    #Features's page images
    - assets/GIF/Features/gif1.json
    - assets/GIF/Features/gif2.json
    - assets/GIF/Features/gif3.json
    - assets/GIF/Features/gif4.json
    - assets/GIF/Features/gif5.json
    - assets/GIF/Features/getStarted.json

    #Questions's page images
    - assets/GIF/Questions/Qgif1.json
    - assets/GIF/Questions/Qgif2.json
    - assets/GIF/Questions/Qgif3.json
    - assets/GIF/Questions/Qgif4.json
    - assets/GIF/Questions/Qgif5.json

    #Registration page images
    - assets/GIF/Registration/signin.json
    - assets/GIF/Registration/signup.json
    - assets/GIF/Registration/password.json

    #Visualize Gif images
    - assets/GIF/Visualise/VZ1.json
    - assets/GIF/Visualise/VZ2.json
    - assets/GIF/Visualise/VZ3.json
    - assets/GIF/Visualise/VZ4.json
    - assets/GIF/Visualise/VZ1.json

    #Audio file
    - assets/audio/

    #CardView stuff
    - assets/GIF/Card_view/1_morning_meditation.json
    - assets/GIF/Card_view/2_night_music.json
    - assets/GIF/Card_view/3_gratitude.json
    - assets/GIF/Card_view/4_mental_marathon.json
    - assets/GIF/Card_view/5_sherlock.json
    - assets/GIF/Card_view/6_thoughts.json
    - assets/GIF/Card_view/7_study_music.json
    - assets/GIF/Card_view/8_kindness.json
    - assets/GIF/Card_view/9_upcoming_events.json
    - assets/GIF/Card_view/10_music.json

    #sherlockHolmes
    - assets/SherlockHolmes/1.jpg
    - assets/SherlockHolmes/2.jpg
    - assets/SherlockHolmes/3.jpg
    - assets/SherlockHolmes/4.jpg
    - assets/SherlockHolmes/5.jpg
    - assets/SherlockHolmes/6.jpg
    - assets/SherlockHolmes/7.jpg
    - assets/SherlockHolmes/8.jpg
    - assets/SherlockHolmes/9.jpg
    - assets/SherlockHolmes/10.jpg

    #Quotes iamges
    - assets/Images/quotes/Swami_Vivekananda.jpg
    - assets/Images/quotes/Virat_Kohli.jpg
    - assets/Images/quotes/Dhoni.jpg
    - assets/Images/quotes/dr_apj.jpg
    - assets/Images/quotes/GuruGopalDas.jpg
    - assets/Images/quotes/Andrew_Tate.jpg
    - assets/Images/quotes/Sadhguru.jpg
    - assets/Images/quotes/elon_musk.jpg
    - assets/Images/quotes/bill_gates.jpg
    - assets/Images/quotes/al_en.jpg

    #persons separate images
    #albert kaka
    - assets/Images/persons/AlbertEinstein/1.jpg
    - assets/Images/persons/AlbertEinstein/2.jpg
    - assets/Images/persons/AlbertEinstein/3.jpg
    - assets/Images/persons/AlbertEinstein/4.jpg
    - assets/Images/persons/AlbertEinstein/5.jpg
    - assets/Images/persons/AlbertEinstein/6.jpg
    - assets/Images/persons/AlbertEinstein/7.jpg
    - assets/Images/persons/AlbertEinstein/8.jpg
    - assets/Images/persons/AlbertEinstein/9.jpg
    - assets/Images/persons/AlbertEinstein/10.jpg

      #andrew kaka
    - assets/Images/persons/AndrewTate/1.jpg
    - assets/Images/persons/AndrewTate/2.jpg
    - assets/Images/persons/AndrewTate/3.jpg
    - assets/Images/persons/AndrewTate/4.jpg
    - assets/Images/persons/AndrewTate/5.jpg
    - assets/Images/persons/AndrewTate/6.jpg
    - assets/Images/persons/AndrewTate/7.jpg
    - assets/Images/persons/AndrewTate/8.jpg
    - assets/Images/persons/AndrewTate/9.jpg
    - assets/Images/persons/AndrewTate/10.jpg

      #apj kaka
    - assets/Images/persons/APJ/1.jpg
    - assets/Images/persons/APJ/2.jpg
    - assets/Images/persons/APJ/3.jpg
    - assets/Images/persons/APJ/4.jpg
    - assets/Images/persons/APJ/5.jpg
    - assets/Images/persons/APJ/6.jpg
    - assets/Images/persons/APJ/7.jpg
    - assets/Images/persons/APJ/8.jpg
    - assets/Images/persons/APJ/9.jpg
    - assets/Images/persons/APJ/10.jpg

      #bill kaka
    - assets/Images/persons/BillGates/1.jpg
    - assets/Images/persons/BillGates/2.jpg
    - assets/Images/persons/BillGates/3.jpg
    - assets/Images/persons/BillGates/4.jpg
    - assets/Images/persons/BillGates/5.jpg
    - assets/Images/persons/BillGates/6.jpg
    - assets/Images/persons/BillGates/7.jpg
    - assets/Images/persons/BillGates/8.jpg
    - assets/Images/persons/BillGates/9.jpg
    - assets/Images/persons/BillGates/10.jpg

      #elon kaka
    - assets/Images/persons/ElonMusk/1.jpg
    - assets/Images/persons/ElonMusk/2.jpg
    - assets/Images/persons/ElonMusk/3.jpg
    - assets/Images/persons/ElonMusk/4.jpg
    - assets/Images/persons/ElonMusk/5.jpg
    - assets/Images/persons/ElonMusk/6.jpg
    - assets/Images/persons/ElonMusk/7.jpg
    - assets/Images/persons/ElonMusk/8.jpg
    - assets/Images/persons/ElonMusk/9.jpg
    - assets/Images/persons/ElonMusk/10.jpg

      #guru gopal dasji
    - assets/Images/persons/GuruGopalDas/1.jpg
    - assets/Images/persons/GuruGopalDas/2.jpg
    - assets/Images/persons/GuruGopalDas/3.jpg
    - assets/Images/persons/GuruGopalDas/4.jpg
    - assets/Images/persons/GuruGopalDas/5.jpg
    - assets/Images/persons/GuruGopalDas/6.jpg
    - assets/Images/persons/GuruGopalDas/7.jpg
    - assets/Images/persons/GuruGopalDas/8.jpg
    - assets/Images/persons/GuruGopalDas/9.jpg
    - assets/Images/persons/GuruGopalDas/10.jpg

      #ms kaka
    - assets/Images/persons/MSD/1.jpg
    - assets/Images/persons/MSD/2.jpg
    - assets/Images/persons/MSD/3.jpg
    - assets/Images/persons/MSD/4.jpg
    - assets/Images/persons/MSD/5.jpg
    - assets/Images/persons/MSD/6.jpg
    - assets/Images/persons/MSD/7.jpg
    - assets/Images/persons/MSD/8.jpg
    - assets/Images/persons/MSD/9.jpg
    - assets/Images/persons/MSD/10.jpg

      #sadhGuru
    - assets/Images/persons/SadhGuru/1.jpg
    - assets/Images/persons/SadhGuru/2.jpg
    - assets/Images/persons/SadhGuru/3.jpg
    - assets/Images/persons/SadhGuru/4.jpg
    - assets/Images/persons/SadhGuru/5.jpg
    - assets/Images/persons/SadhGuru/6.jpg
    - assets/Images/persons/SadhGuru/7.jpg
    - assets/Images/persons/SadhGuru/8.jpg
    - assets/Images/persons/SadhGuru/9.jpg
    - assets/Images/persons/SadhGuru/10.jpg

      #swami vivekananda
    - assets/Images/persons/SwamiVivekananda/1.jpg
    - assets/Images/persons/SwamiVivekananda/2.jpg
    - assets/Images/persons/SwamiVivekananda/3.jpg
    - assets/Images/persons/SwamiVivekananda/4.jpg
    - assets/Images/persons/SwamiVivekananda/5.jpg
    - assets/Images/persons/SwamiVivekananda/6.jpg
    - assets/Images/persons/SwamiVivekananda/7.jpg
    - assets/Images/persons/SwamiVivekananda/8.jpg
    - assets/Images/persons/SwamiVivekananda/9.jpg
    - assets/Images/persons/SwamiVivekananda/10.jpg

      #virat kohli
    - assets/Images/persons/ViratKohli/1.jpg
    - assets/Images/persons/ViratKohli/2.jpg
    - assets/Images/persons/ViratKohli/3.jpg
    - assets/Images/persons/ViratKohli/4.jpg
    - assets/Images/persons/ViratKohli/5.jpg
    - assets/Images/persons/ViratKohli/6.jpg
    - assets/Images/persons/ViratKohli/7.jpg
    - assets/Images/persons/ViratKohli/8.jpeg
    - assets/Images/persons/ViratKohli/9.jpg
    - assets/Images/persons/ViratKohli/10.jpg

    #types_images
    - assets/Images/types_quotes/gym_1.jpg
    - assets/Images/types_quotes/diet.jpg
    - assets/Images/types_quotes/education.jpg
    - assets/Images/types_quotes/financial.jpg
    - assets/Images/types_quotes/career.jpg
    - assets/Images/types_quotes/mentalhealth.jpg
    - assets/Images/types_quotes/productivity.jpg
    - assets/Images/types_quotes/Self-Improvement.jpg
    - assets/Images/types_quotes/sociallife.jpg
    - assets/Images/types_quotes/Motivation.jpg

    #music images
    - assets/Images/Music/ms_1.jpg
    - assets/Images/Music/ms_2.jpg
    - assets/Images/Music/ms_3.jpg
    - assets/Images/Music/ms_4.jpg

    #Morning Meditation images/svg/json.
    - assets/Images/Morning_meditation/vs_1.jpg
    - assets/Images/Morning_meditation/vs_2.jpg
    - assets/Images/Morning_meditation/vs_3.jpg
    - assets/Images/Morning_meditation/vs_4.jpg

    #Night music
    - assets/Images/night_music/nm_1.jpg
    - assets/Images/night_music/nm_2.jpg
    - assets/Images/night_music/nm_3.jpg
    - assets/Images/night_music/nm_4.jpg
    - assets/Images/night_music/nm_5.jpg
    - assets/Images/night_music/nm_6.jpg
    - assets/Images/night_music/nm_7.jpg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
